    // "generate-types": "npx openapi-typescript https://oiprtsmygibfmxvpsbpr.supabase.co/rest/v1/\?apikey\=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYzODE2NTgzNCwiZXhwIjoxOTUzNzQxODM0fQ.DX3vlLx8Vw5-mcuOWc0p5PjCEs6rgw6AAYKLqJgA4KI --output src/supabase/types.ts"
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/case-studies": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.case-studies.id"];
          name?: parameters["rowFilter.case-studies.name"];
          description?: parameters["rowFilter.case-studies.description"];
          discussion_question?: parameters["rowFilter.case-studies.discussion_question"];
          video_url?: parameters["rowFilter.case-studies.video_url"];
          thumbnail_url?: parameters["rowFilter.case-studies.thumbnail_url"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["case-studies"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** case-studies */
          "case-studies"?: definitions["case-studies"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.case-studies.id"];
          name?: parameters["rowFilter.case-studies.name"];
          description?: parameters["rowFilter.case-studies.description"];
          discussion_question?: parameters["rowFilter.case-studies.discussion_question"];
          video_url?: parameters["rowFilter.case-studies.video_url"];
          thumbnail_url?: parameters["rowFilter.case-studies.thumbnail_url"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.case-studies.id"];
          name?: parameters["rowFilter.case-studies.name"];
          description?: parameters["rowFilter.case-studies.description"];
          discussion_question?: parameters["rowFilter.case-studies.discussion_question"];
          video_url?: parameters["rowFilter.case-studies.video_url"];
          thumbnail_url?: parameters["rowFilter.case-studies.thumbnail_url"];
        };
        body: {
          /** case-studies */
          "case-studies"?: definitions["case-studies"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** Holds a list of case studies. */
  "case-studies": {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    name?: string;
    description?: string;
    discussion_question?: string;
    video_url?: string;
    thumbnail_url?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** case-studies */
  "body.case-studies": definitions["case-studies"];
  "rowFilter.case-studies.id": string;
  "rowFilter.case-studies.name": string;
  "rowFilter.case-studies.description": string;
  "rowFilter.case-studies.discussion_question": string;
  "rowFilter.case-studies.video_url": string;
  "rowFilter.case-studies.thumbnail_url": string;
}

export interface operations {}

export interface external {}
